### ISSUE TITLE
Git push issue

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3620/docs#1]
When i try to execute the add command there is no message in response.  And then when i try to execute the commit command this message comes up:

Michael-Zelaskos-MacBook-Pro:Sources mgzelasko$ git add main.cpp
Michael-Zelaskos-MacBook-Pro:Sources mgzelasko$ git commit -m "Hw upload feb 4 1:41pm"
[master a22d9de] Hw upload feb 4 1:41pm
 Committer: Michael Zelasko <mgzelasko@Michael-Zelaskos-MacBook-Pro.local>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 10 files changed, 427 insertions(+), 3 deletions(-)
 create mode 100644 .DS_Store
 create mode 100644 Glitter/.DS_Store
 create mode 100644 Glitter/Vendor/.DS_Store
 create mode 100644 Goo/Goo.xcodeproj/project.pbxproj
 create mode 100644 Goo/Goo.xcodeproj/project.xcworkspace/contents.xcworkspacedata
 create mode 100644 Goo/Goo.xcodeproj/project.xcworkspace/xcuserdata/mgzelasko.xcuserdatad/UserInterfaceState.xcuserstate
 create mode 100644 Goo/Goo.xcodeproj/xcuserdata/mgzelasko.xcuserdatad/xcschemes/Goo.xcscheme
 create mode 100644 Goo/Goo.xcodeproj/xcuserdata/mgzelasko.xcuserdatad/xcschemes/xcschememanagement.plist
 create mode 100644 Goo/Goo/main.cpp

And i get the following error message when i try to execute the next command:

Michael-Zelaskos-MacBook-Pro:Sources mgzelasko$ git push origin hw
error: src refspec hw does not match any.

i am not sure what is wrong or how to solve this issue

**Comment by TS96** [comment]
It seems like someone else had the same issue and posted about it in the "1-open-window" repository. The solution that the professor gave was to try "git push origin HEAD:hw" instead of "git push origin hw".

**Comment by MichaelGregg** [comment]
Thanks for the help, When i type the new command, this is the message i receive in response:
Michael-Zelaskos-MacBook-Pro:Sources mgzelasko$ git push origin HEAD:hw
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/cisc3620/1-open-window-MichaelGregg.git
   3f9b8e6..a22d9de  HEAD -> hw
When i move to the next step, “hw” does not show up for me to add to the compare button:
Im not sure what to do from here

**Comment by TS96** [comment]
Make sure that your commit was pushed to github. Go to the private repository that was created for you, switch to the hw branch then look at the commit history and make sure that yours is there. If it's there, then I don't see why you wouldn't be able to start a pull request.

**Comment by rivlev** [comment]
Please close this issue if it was resolved.
