### ISSUE TITLE
src refspec hw does not match any

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3620/docs#6]
<@rivlev deleted full code>

But git is not working.  When i try to add main.cpp from the 2-draw-triangle level of the directory i get this:

fatal: pathspec 'main.cpp' did not match any files

But if i navigate to Sources, the directory in which main is, when i do git add main.cpp i get no message in response, so then i do git commit, which gives me this:

On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Untracked files:
	../../.DS_Store
	../.DS_Store

nothing added to commit but untracked files present

I dont think that is what should come back as a response.  I then try git push origin hw which gives me this:

error: src refspec hw does not match any.
error: failed to push some refs to 'https://github.com/cisc3620/2-draw-triangle.git'

I have the assignment completed correctly, what do i need to do in order to properly submit it?

**Comment by MichaelGregg** [comment]
I have tried several times starting over from the beginning following the exact instructions but something is clearly wrong because it will no work.  i now get this message when i try the commit command:

J3611-B1-49330:2-draw-triangle mgzelasko$ git commit -m "message"
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
Untracked files:
	.DS_Store
	Glitter/.DS_Store

nothing added to commit but untracked files present
J3611-B1-49330:2-draw-triangle mgzelasko$ git push origin hw
error: src refspec hw does not match any.
error: failed to push some refs to 'https://github.com/cisc3620/2-draw-triangle.git'

**Comment by rivlev** [comment]
I removed the code from your comment, please do not post full solutions

**Comment by rivlev** [comment]
For some reason your repository is tracking the original -- 2-draw-triangle -- instead of the private repository created for you -- 2-draw-triangle-MichaelGregg. You don't have write permissions for the original repository.

**Comment by MichaelGregg** [comment]
What should i do to fix this?

**Comment by rivlev** [comment]
You only have one branch in your 2-draw-triangle-MichaelGregg repository. You can't push to hw because it doesn't exist. The hw branch should be created and checked out before you make any changes.

Create the homework branch now: ```git checkout -b hw'''
Then go back to master: ```git checkout master'''
Do ```git reset --hard 84d978b'''
This will forcibly roll back all changes on the master branch to the commit before you made any changes.
You now should be able to do the pull request from hw to master.
